---
- name: Test Playbok
  hosts: 192.168.10.62
  remote_user: root
  gather_facts: False

  tasks:
  - name: Upgrade all packages, excluding kernel & foo related packages
    ansible.builtin.yum:
      name: '*'
      state: latest
      exclude: kernel*
