---
- name: Update web servers
  hosts: 192.168.10.62
  remote_user: root

  tasks:
  - name: Upgrade all packages, excluding kernel & foo related packages
    ansible.builtin.yum:
      name: '*'
      state: latest
      exclude: kernel*
